routes/web.php
<?php

//use App\Http\Controllers\Management\CategoryController;

Route::get('/', 'HomeController@index');

Auth::routes(['register' => false, 'reset' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {
    //cashier
    Route::get('/cashier', 'Cashier\CashierController@index')->name('cashier');
    Route::get('/cashier/get-table', 'Cashier\CashierController@getTables')->name('cashier-get-tables');
    Route::get('/cashier/getSaleDetailsByTable/{table_id}', 'Cashier\CashierController@getSaleDetailsByTable')->name('cashier-get-sale-details-by-table');
    Route::get('/cashier/getMenuByCategory/{category_id}', 'Cashier\CashierController@getMenuByCategory')->name('cashier-get-menu-by-category');
    Route::post('/cashier/orderFood', 'Cashier\CashierController@orderFood')->name('cashier-order-food');
    Route::post('/cashier/confirmOrderStatus', 'Cashier\CashierController@confirmOrderStatus');
    Route::post('/cashier/deleteSaleDetail', 'Cashier\CashierController@deleteSaleDetail');
    Route::post('/cashier/increase-quantity', 'Cashier\CashierController@increaseQuantity');
    Route::post('/cashier/decrease-quantity', 'Cashier\CashierController@decreaseQuantity');
    Route::post('/cashier/savePayment', 'Cashier\CashierController@savePayment');
    Route::get('/cashier/showReceipt/{saleID}', 'Cashier\CashierController@showReceipt');

});
Route::middleware(['auth', 'VerifyAdmin'])->group(function () {
//report
    Route::get('/report', 'Report\ReportController@index')->name('report');
    Route::get('/report/show', 'Report\ReportController@show')->name('report-show');

// export to excel
    Route::get('/report/show/export', 'Report\ReportController@export')->name('report-export');

    Route::get('/management', function() {
        return view('management/index');
    })->name('management.index');
    Route::resource('management/categories', 'Management\CategoryController');
    Route::resource('management/menu', 'Management\MenuController');
    Route::resource('management/tables', 'Management\TableController');
    Route::resource('management/users', 'Management\UserController');
});

app/Http/Controllers/Management/CategoryController.php
<?php

namespace App\Http\Controllers\Management;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\View\View;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $categories = Category::paginate(10);
        return view('management.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('management.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:categories|max:255'
        ]);
        $category = new Category();
        $category->name = $request->name;
        $category->slug = Str::slug($request->name);
        $category->save();
        $request->session()->flash('status', 'Category created successfully');
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Category $category
     * @return Application|Factory|View
     */
    public function edit(Category $category)
    {
        return view('management.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Category $category
     * @return void
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'name' => 'required|unique:categories|max:255'
        ]);
        $category->name = $request->name;
        $category->slug = Str::slug($request->name);
        $category->save();
        $request->session()->flash('status', 'Category updated successfully');
        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Category $category
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy(Category $category)
    {
        $category->delete();
        session()->flash('status', 'Category deleted successfully');
        return redirect()->route('categories.index');
    }
}

app/Http/Controllers/Management/MenuController.php
<?php

namespace App\Http\Controllers\Management;

use App\Category;
use App\Http\Controllers\Controller;
use App\Menu;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $menus = Menu::paginate(10);
        return view('management.menu.index', compact('menus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        $categories = Category::all();
        return view('management.menu.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:menus|max:255',
            'price' => 'required|numeric',
            'category_id' => 'required|numeric',
        ]);

        $imageName = 'noimage.png';
        if($request->image) {
            $request->validate([
                'image' => 'nullable|file|image|mimes:jpeg, png, jpg|max:5000',
            ]);
            $imageName = date('mdYHis').uniqid() . '.' . $request->image->extension();
            $request->image->move(public_path('images/menu'), $imageName);
        }
        $menu = new Menu();
        $menu->name = $request->name;
        $menu->price = $request->price;
        $menu->image = $imageName;
        $menu->description = $request->description;
        $menu->category_id = $request->category_id;
        $menu->save();
        session()->flash('status', 'Menu has been created successfully');
        return redirect()->route('menu.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Menu $menu
     * @return Application|Factory|View
     */
    public function edit(Menu $menu)
    {
        $categories = Category::all();
        return view('management.menu.edit', compact('menu', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Menu $menu
     * @return RedirectResponse
     */
    public function update(Request $request, Menu $menu)
    {
        $request->validate([
            'name' => 'required|max:255',
            'price' => 'required|numeric',
            'category_id' => 'required|numeric',
        ]);

        if($request->image) {
            $request->validate([
                'image' => 'nullable|file|image|mimes:jpeg, png, jpg|max:5000',
            ]);
            if($menu->image != 'noimage.png') {
                $imageName = $menu->image;
                unlink(public_path('images/menu') . '/' . $imageName);
            }
            $imageName = date('mdYHis').uniqid() . '.' . $request->image->extension();
            $request->image->move(public_path('images/menu'), $imageName);
        }else {
            $imageName = $menu->image;
        }

        $menu->name = $request->name;
        $menu->price = $request->price;
        $menu->image = $imageName;
        $menu->description = $request->description;
        $menu->category_id = $request->category_id;
        $menu->save();
        session()->flash('status', 'Menu has been created successfully');
        return redirect()->route('menu.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Menu $menu)
    {
        if($menu->image != 'noimage.png') {
            unlink(public_path('images/menu') . '/' . $menu->image);
        }
        $menu->delete();
        session()->flash('status', 'Menu has been deleted successfully');
        return redirect()->route('menu.index');
    }
}

app/Http/Controllers/Management/TableController.php
<?php

namespace App\Http\Controllers\Management;

use App\Http\Controllers\Controller;
use App\Table;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class TableController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $tables = Table::paginate(2);
        return view('management.table.index', compact('tables'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('management.table.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:tables|max:255',
        ]);
        $table = new Table();
        $table->name = $request->name;
        $table->save();
        session()->flash('status', 'Table has been created successfully');
        return redirect()->route('tables.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Table $table)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Table $table
     * @return Application|Factory|View
     */
    public function edit(Table $table)
    {
        return view('management.table.edit', compact('table'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Table $table
     * @return RedirectResponse
     */
    public function update(Request $request, Table $table)
    {
        $request->validate([
            'name' => 'required|unique:tables|max:255',
        ]);
        $table->name = $request->name;
        $table->save();
        session()->flash('status', 'Table has been updated successfully');
        return redirect()->route('tables.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Table $table
     * @return void
     * @throws \Exception
     */
    public function destroy(Table $table)
    {
        $table->delete();
        session()->flash('status', 'Table has been deleted successfully');
        return redirect()->route('tables.index');
    }
}

app/Http/Controllers/Management/UserController.php
<?php

namespace App\Http\Controllers\Management;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rule;
use Illuminate\View\View;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $users = User::paginate(7);
        return view('management.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('management.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:users|max:255',
            'email' => 'required|email|unique:users|max:255',
            'password' => 'required|min:6',
            'role' => 'required',
        ]);
        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->role = $request->role;
        $user->save();
        session()->flash('status', 'New user has been created successfully');
        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('management.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'name' => [
                'required',
                'max:255',
                Rule::unique('users')->ignore($user->id),
            ],
            'email' => [
                'required',
                'email',
                'max:255',
                Rule::unique('users')->ignore($user->id),
            ],
            'password' => 'nullable|min:6',
            'role' => 'required',
        ]);
        $user->name = $request->name;
        $user->email = $request->email;
        if($request->password) {
            $user->password = Hash::make($request->password);
        }
        $user->role = $request->role;
        $user->save();
        session()->flash('status', 'User has been updated successfully');
        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        session()->flash('status', 'User has been deleted successfully');
        return redirect()->route('users.index');
    }
}

resources/views/management/table/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-start">
            @include('management.inc.sidebar')
            <div class="col-md-8">
                <i class="fas fa-chair mr-1"></i>Create New Table
                <a href="{{ route('tables.index') }}" class="btn btn-warning btn-sm float-right"><i class="fa-solid fa-angle-left"></i>Back</a>
                <hr>
                <form action="{{ route('tables.store') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="tableName">Table Name</label>
                        <input type="text" name="name" class="form-control" placeholder="Table...">
                        @error('name') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/management/table/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-start">
            @include('management.inc.sidebar')
            <div class="col-md-8">
                <i class="fas fa-chair mr-1"></i>Edit Table
                <a href="{{ route('tables.index') }}" class="btn btn-warning btn-sm float-right"><i class="fa-solid fa-angle-left"></i>Back</a>
                <hr>
                <form action="{{ route('tables.update', $table) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="tableName">Table Name</label>
                        <input type="text" name="name" class="form-control" value="{{ $table->name }}">
                        @error('name') <span class="text-danger error">{{ $message }}</span>@enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/management/table/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-start">
            @include('management.inc.sidebar')
            <div class="col-md-8">
                <i class="fas fa-chair mr-1"></i>Table
                <a href="{{ route('tables.create') }}" class="btn btn-success btn-sm float-right"><i class="fas fa-plus mr-1"></i>Create New Table</a>
                <hr>
                @if(Session()->has('status'))
                    <div class="alert alert-success" role="alert">{{ Session()->get('status') }}</div>
                @endif
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Table</th>
                            <th scope="col">Status</th>
                            <th scope="col">Edit</th>
                            <th scope="col">Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($tables as $table)
                            <tr>
                                <th scope="row">{{ $table->id }}</th>
                                <td>{{ $table->name }}</td>
                                <td>{{ $table->status }}</td>
                                <td>
                                    <a href="{{ route('tables.edit', $table) }}" class="btn btn-warning">Edit</a>
                                </td>
                                <td>
                                    <form action="{{ route('tables.destroy', $table) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $tables->links() }}
            </div>
        </div>
    </div>
@endsection